name: 🚀 CI & Release

on:
  push:
    branches:
      - main
      - develop
      - 'release/*'

permissions:
  contents: write
  issues: write
  pull-requests: write
  
jobs:
  semantic-release:
    name: Release & Changelog (GitHub)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.8.1'

      - name: Install dependencies
        run: npm ci

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  publish-npm:
    name: Publish to npmjs.org
    needs: semantic-release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Node.js & authenticate
        uses: actions/setup-node@v4
        with:
          node-version: '20.8.1'
          registry-url: 'https://registry.npmjs.org/'

      - name: Create .npmrc for npmjs.org
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm ci

      - name: Build (if applicable)
        run: npm run build

      - name: Publish to npmjs.org
        run: npm publish --access public
